name: CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v7
        with:
          start: npm start
          wait-on: "http://localhost:5500"
          browser: chrome